import { mumbai } from './chains';

const CONFIGURED_GAS_LIMIT_MULTIPLIERS = {
  [mumbai.id]: 10,
};

const DEFAULT_GAS_LIMIT_MULTIPLIER = 1;

export { CONFIGURED_GAS_LIMIT_MULTIPLIERS, DEFAULT_GAS_LIMIT_MULTIPLIER };
