const CONFIGURED_RULE_TYPES = {
  PUREFI_KYC1: 0,
  PUREFI_KYC2: 1,
};

const DEFAULT_RULE_TYPE_VALUES = {
  [CONFIGURED_RULE_TYPES.PUREFI_KYC1]: '776',
  [CONFIGURED_RULE_TYPES.PUREFI_KYC2]: '777',
};

const RULE_TYPE_OPTIONS = [
  {
    label: 'PUREFI KYC (LVL 1)',
    value: CONFIGURED_RULE_TYPES.PUREFI_KYC1,
  },
  {
    label: 'PUREFI KYC (LVL 2)',
    value: CONFIGURED_RULE_TYPES.PUREFI_KYC2,
  },
];

const DEFAULT_RULE_TYPE = CONFIGURED_RULE_TYPES.PUREFI_KYC1;
const LVL1_RULE_VALUE =
  DEFAULT_RULE_TYPE_VALUES[CONFIGURED_RULE_TYPES.PUREFI_KYC1];
const LVL2_RULE_VALUE =
  DEFAULT_RULE_TYPE_VALUES[CONFIGURED_RULE_TYPES.PUREFI_KYC2];

export {
  CONFIGURED_RULE_TYPES,
  DEFAULT_RULE_TYPE_VALUES,
  RULE_TYPE_OPTIONS,
  DEFAULT_RULE_TYPE,
  LVL1_RULE_VALUE,
  LVL2_RULE_VALUE,
};
